version: "3.8"
services:
  main:
    container_name: schoolorga.server
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - ./:/var/www/html/
      - ./docker/index.php:/var/www/html/public/index.php
    ports:
      - "9030:8000"

  queue:
    container_name: schoolorga.queue
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: schoolorga.db
    environment:
      MYSQL_DATABASE: schoolorga
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_schoolorga:/var/lib/mysql
    ports:
      - "3340:3306"

  mailpit:
    image: axllent/mailpit
    container_name: schoolorga.mail
    ports:
      - "1525:1025"
      - "7025:8025"

volumes:
  db_schoolorga:
    driver: local
